---
- hosts: localhost
  tasks:
    - name: Get IPv4 address
      ansible.builtin.shell: hostname -I | awk '{print $1}'
      register: ipv4_address

    - name: Display IPv4 address
      ansible.builtin.debug:
        var: ipv4_address.stdout
